console.log("Hi");
//npm init

const http=require('http');
const server=http.createServer((req,res)=>{
    console.log("generated by index file from Node app")
    res.write("Welcome to node app");
    res.end();

})

//server.listen(process.env.PORT);
server.listen(3000);

/*

RUN VS CMD 
-
-RUN RUNS APP DURING THE IMAGE 

OS Linux
NodeJs SW
Port(3000)
index.js
package.json

cmd terminal
--------------
node index.js
 */